# Tensorflow

Tensorflow trabalha com "Tensores", matrizes de n dimensões. O Tensores passam por operações, resultando em novos Tensores. A sequência de operações de Tensores compõem Grafos. Uma Sessão corresponde a uma tradução dos Grafos em comandos para a GPU e CPU, para executar essa computação.
<img src='https://ibm.box.com/shared/static/a94cgezzwbkrq02jzfjjljrcaozu5s2q.png'>

In [2]:
import tensorflow as tf

## 1) Grafos
Do curso [Deep Learning with Tensorflow - Module 1 - Lab: Hello World](https://courses.edx.org/courses/course-v1:IBM+DL0120EN+3T2018/course/):
<div class="alert alert-success alertsuccess" style="margin-top: 20px">

> <font size = 3><strong>In TensorFlow all data is passed between operations in a computation graph, and these are passed in the form of Tensors, hence the name of TensorFlow.</strong></font>
<br>
<br>
    The word <b>tensor</b> from new latin means "that which stretches". It is a mathematical object that is named "tensor" because an early application of tensors was the study of materials stretching under tension. The contemporary meaning of tensors can be taken as multidimensional arrays. 



</div>

> That's great, but... what are these multidimensional arrays? 

> Going back a little bit to physics to understand the concept of dimensions:<br>
<img src="https://ibm.box.com/shared/static/ymn0hl3hf8s3xb4k15v22y5vmuodnue1.svg"/>
<div style="text-align:center"><a href="https://en.wikipedia.org/wiki/Dimension">Image Source</a></div>
<br>

> The zero dimension can be seen as a point, a single object or a single item.

> The first dimension can be seen as a line, a one-dimensional array can be seen as numbers along this line, or as points along the line. One dimension can contain infinite zero dimension/points elements.

> The second dimension can be seen as a surface, a two-dimensional array can be seen as an infinite series of lines along an infinite line. 

> The third dimension can be seen as volume, a three-dimensional array can be seen as an infinite series of surfaces along an infinite line.

>The Fourth dimension can be seen as the hyperspace or spacetime, a volume varying through time, or an infinite series of volumes along an infinite line. And so forth on...

> As mathematical objects: <br><br>
<img src="https://ibm.box.com/shared/static/kmxz570uai8eeg6i6ynqdz6kmlx1m422.png">
<div style="text-align: center"><a href="https://book.mql4.com/variables/arrays">Image Source</a></div>

In [3]:
graph1 = tf.Graph()

In [4]:
with graph1.as_default():
    a = tf.constant([[1,2,3],[2,3,4],[3,4,5]])
    b = tf.constant([[2,2,2],[2,2,2],[2,2,2]])
    # operações com tensores
    c = a + b # ou tf.add(a,b)
    d = a * b
    e = tf.matmul(a,b)

In [5]:
with tf.Session(graph = graph1) as sess:
    result = sess.run(c)
    print("Soma de matrizes")
    print(result)
    result = sess.run(d)
    print("\nMultiplicação de Hadamard")
    print(result)
    result = sess.run(e)
    print("\nMultiplicação de matrizes")
    print(result)

Soma de matrizes
[[3 4 5]
 [4 5 6]
 [5 6 7]]

Multiplicação de Hadamard
[[ 2  4  6]
 [ 4  6  8]
 [ 6  8 10]]

Multiplicação de matrizes
[[12 12 12]
 [18 18 18]
 [24 24 24]]


Outras operações são encontradas na documentação: https://www.tensorflow.org/api_docs/python/tf

## 2) Tensores?
Tensores fazem sentido para trabalhar dados de diversas dimensões. Sejam esses dados tabelas com m linhas por n colunas (2 dimensões) ou imagens com 3 canais de cores, altura h e largura w (3 dimensões). A manipulação dessas informações se faz muito mais simples com sua imlementação a partir do Tensorflow.

## 3) Variáveis
Variáveis definem informações persistentes ao longo do programa, diferente dos tensores em si, que são definidos apenas dentro das Sessões, podendo ser alteradas ao longo do tempo, com novas iterações e diferentes sessões.

As variáveis são definidas por meio da chamada ```tf.Variable```.

In [6]:
v = tf.Variable(0)

In [7]:
# counter
update = tf.assign(v, v+1) # tf.assign(reference_variable, value_to_update)

In [8]:
init_op = tf.global_variables_initializer()

In [9]:
with tf.Session() as session:
    session.run(init_op)
    print(session.run(v))
    for _ in range(3):
        session.run(update)
        print(session.run(v))

0
1
2
3


## 4) Placeholders
Quando o valor do tensor não é definido, podemos fazer operações com variáveis, sendo definidas apenas no momento de iniciar a sessão. Eles são definidos da seguinte forma:

|Data type	|Python type|Description|
| --------- | --------- | --------- |
|DT_FLOAT	|tf.float32	|32 bits floating point.|
|DT_DOUBLE	|tf.float64	|64 bits floating point.|
|DT_INT8	|tf.int8	|8 bits signed integer.|
|DT_INT16	|tf.int16	|16 bits signed integer.|
|DT_INT32	|tf.int32	|32 bits signed integer.|
|DT_INT64	|tf.int64	|64 bits signed integer.|
|DT_UINT8	|tf.uint8	|8 bits unsigned integer.|
|DT_STRING	|tf.string	|Variable length byte arrays. Each element of a Tensor is a byte array.|
|DT_BOOL	|tf.bool	|Boolean.|
|DT_COMPLEX64	|tf.complex64	|Complex number made of two 32 bits floating points: real and imaginary parts.|
|DT_COMPLEX128	|tf.complex128	|Complex number made of two 64 bits floating points: real and imaginary parts.|
|DT_QINT8	|tf.qint8	|8 bits signed integer used in quantized Ops.|
|DT_QINT32	|tf.qint32	|32 bits signed integer used in quantized Ops.|
|DT_QUINT8	|tf.quint8	|8 bits unsigned integer used in quantized Ops.|

In [10]:
a = tf.placeholder(tf.float32)

In [11]:
b = a * 2

In [12]:
dictionary={a: [ [ [1,2,3],[4,5,6],[7,8,9],[10,11,12] ] , [ [13,14,15],[16,17,18],[19,20,21],[22,23,24] ] ] }

with tf.Session() as sess:
    result = sess.run(b,feed_dict=dictionary)
    print (result)

[[[ 2.  4.  6.]
  [ 8. 10. 12.]
  [14. 16. 18.]
  [20. 22. 24.]]

 [[26. 28. 30.]
  [32. 34. 36.]
  [38. 40. 42.]
  [44. 46. 48.]]]


Devemos passar em forma de dicionário (nome da variável usada como placeholder e seu valor).